version: "3.3"
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  api:
    build: ./api
    privileged: true
    depends_on:
      - db
    volumes:
      - ./api:/var/www/api

  app:
    build: ./app
    depends_on:
      - api
    volumes:
      - ./app:/var/www/app

  nginx:
    image: nginx:latest
    depends_on:
      - app
      - api
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app:/var/www/app
      - ./api:/var/www/api
    ports:
      - 80:80
      - 8080:8080
    command: [nginx-debug, '-g', 'daemon off;']
